-- SIPLA schema for Supabase PostgreSQL
-- Converted from pengaduan_masyarakat3.sql and aligned with the current Go models.
-- Run this file before seed.sql on a new Supabase project.

BEGIN;

CREATE TABLE IF NOT EXISTS provinces (
    id char(2) PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS regencies (
    id char(4) PRIMARY KEY,
    province_id char(2) NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT regencies_province_id_foreign
        FOREIGN KEY (province_id) REFERENCES provinces(id)
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS regencies_province_id_index ON regencies(province_id);

CREATE TABLE IF NOT EXISTS districts (
    id char(7) PRIMARY KEY,
    regency_id char(4) NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT districts_regency_id_foreign
        FOREIGN KEY (regency_id) REFERENCES regencies(id)
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS districts_regency_id_index ON districts(regency_id);

CREATE TABLE IF NOT EXISTS villages (
    id char(10) PRIMARY KEY,
    district_id char(7) NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT villages_district_id_foreign
        FOREIGN KEY (district_id) REFERENCES districts(id)
        ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS villages_district_id_index ON villages(district_id);

CREATE TABLE IF NOT EXISTS failed_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL UNIQUE,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jenis_layanan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_layanan varchar(100) NOT NULL,
    deskripsi text,
    syarat text,
    estimasi_hari integer DEFAULT 3,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT jenis_layanan_nama_unique UNIQUE (nama_layanan),
    CONSTRAINT jenis_layanan_estimasi_check CHECK (estimasi_hari >= 0)
);

CREATE TABLE IF NOT EXISTS kelurahan_info (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama varchar(100) NOT NULL DEFAULT 'Serua Indah',
    kecamatan varchar(100) NOT NULL DEFAULT 'Ciputat',
    kota varchar(100) NOT NULL DEFAULT 'Tangerang Selatan',
    provinsi varchar(100) NOT NULL DEFAULT 'Banten',
    kode_pos varchar(10) NOT NULL DEFAULT '15414',
    luas_wilayah varchar(50),
    jumlah_penduduk integer,
    jumlah_kk integer,
    jumlah_laki_laki integer NOT NULL DEFAULT 0,
    jumlah_perempuan integer NOT NULL DEFAULT 0,
    jml_paud_kb_tk integer NOT NULL DEFAULT 0,
    jml_sekolah_dasar integer NOT NULL DEFAULT 0,
    jml_sltp integer NOT NULL DEFAULT 0,
    jml_slta integer NOT NULL DEFAULT 0,
    jml_perguruan_tinggi integer NOT NULL DEFAULT 0,
    jml_rumah_sakit integer NOT NULL DEFAULT 0,
    jml_puskesmas integer NOT NULL DEFAULT 0,
    jml_klinik integer NOT NULL DEFAULT 0,
    jml_klinik_tradisional integer NOT NULL DEFAULT 0,
    jml_posyandu integer NOT NULL DEFAULT 0,
    visi text,
    misi text,
    sejarah text,
    foto_kantor varchar(255),
    alamat_kantor text,
    telp_kantor varchar(20),
    email_kantor varchar(100),
    jam_operasional varchar(100),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS masyarakat (
    nik char(16) PRIMARY KEY,
    name varchar(100) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    email_verified_at timestamp,
    username varchar(50) NOT NULL UNIQUE,
    jenis_kelamin varchar(20) NOT NULL,
    password varchar(255) NOT NULL,
    telp varchar(20),
    alamat text,
    rt varchar(4),
    rw varchar(4),
    kode_pos varchar(10),
    province_id char(2),
    regency_id char(4),
    district_id char(7),
    village_id char(10),
    remember_token varchar(100),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT masyarakat_jenis_kelamin_check
        CHECK (jenis_kelamin IN ('Laki-laki', 'Perempuan')),
    CONSTRAINT masyarakat_province_id_foreign
        FOREIGN KEY (province_id) REFERENCES provinces(id) ON UPDATE CASCADE,
    CONSTRAINT masyarakat_regency_id_foreign
        FOREIGN KEY (regency_id) REFERENCES regencies(id) ON UPDATE CASCADE,
    CONSTRAINT masyarakat_district_id_foreign
        FOREIGN KEY (district_id) REFERENCES districts(id) ON UPDATE CASCADE,
    CONSTRAINT masyarakat_village_id_foreign
        FOREIGN KEY (village_id) REFERENCES villages(id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS migrations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration varchar(255) NOT NULL,
    batch integer NOT NULL
);

CREATE TABLE IF NOT EXISTS password_resets (
    email varchar(255) NOT NULL,
    token varchar(255) NOT NULL,
    created_at timestamp
);

CREATE INDEX IF NOT EXISTS password_resets_email_index ON password_resets(email);

CREATE TABLE IF NOT EXISTS petugas (
    id_petugas bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_petugas varchar(100) NOT NULL,
    username varchar(50) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    telp varchar(20),
    roles varchar(20) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT petugas_roles_check CHECK (roles IN ('admin', 'petugas'))
);

CREATE TABLE IF NOT EXISTS pengaduan (
    id_pengaduan bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tgl_pengaduan timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nik char(16) NOT NULL,
    tipe_aspirasi varchar(100),
    judul_laporan varchar(255) NOT NULL,
    isi_laporan text NOT NULL,
    tgl_kejadian timestamptz NOT NULL,
    lokasi_kejadian text NOT NULL,
    latitude numeric(10,8),
    longitude numeric(11,8),
    foto varchar(255) NOT NULL DEFAULT '',
    status varchar(50) NOT NULL DEFAULT 'verifikasi_lapangan',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pengaduan_nik_foreign
        FOREIGN KEY (nik) REFERENCES masyarakat(nik)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT pengaduan_status_check CHECK (
        status IN ('verifikasi_lapangan', 'koordinasi', 'proses_penyelesaian', 'selesai', 'ditolak')
    )
);

CREATE INDEX IF NOT EXISTS pengaduan_nik_index ON pengaduan(nik);
CREATE INDEX IF NOT EXISTS pengaduan_status_index ON pengaduan(status);

CREATE TABLE IF NOT EXISTS permohonan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik char(16) NOT NULL,
    id_jenis_layanan bigint NOT NULL,
    tgl_permohonan timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    keterangan text,
    file_ktp varchar(255),
    file_kk varchar(255),
    file_surat_rtrw varchar(255),
    file_foto_rumah varchar(255),
    file_pendukung varchar(255),
    status varchar(50) NOT NULL DEFAULT 'verifikasi_persyaratan',
    catatan_petugas text,
    file_hasil varchar(255),
    id_petugas bigint,
    tgl_selesai timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permohonan_nik_foreign
        FOREIGN KEY (nik) REFERENCES masyarakat(nik) ON DELETE CASCADE,
    CONSTRAINT permohonan_jenis_foreign
        FOREIGN KEY (id_jenis_layanan) REFERENCES jenis_layanan(id),
    CONSTRAINT permohonan_petugas_foreign
        FOREIGN KEY (id_petugas) REFERENCES petugas(id_petugas) ON DELETE SET NULL,
    CONSTRAINT permohonan_status_check CHECK (
        status IN ('verifikasi_persyaratan', 'pembuatan_draft', 'penandatanganan', 'register_dokumen', 'selesai', 'ditolak')
    )
);

CREATE INDEX IF NOT EXISTS permohonan_nik_index ON permohonan(nik);
CREATE INDEX IF NOT EXISTS permohonan_jenis_index ON permohonan(id_jenis_layanan);
CREATE INDEX IF NOT EXISTS permohonan_petugas_index ON permohonan(id_petugas);
CREATE INDEX IF NOT EXISTS permohonan_status_index ON permohonan(status);

CREATE TABLE IF NOT EXISTS personal_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type varchar(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    token varchar(64) NOT NULL UNIQUE,
    abilities text,
    last_used_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE INDEX IF NOT EXISTS personal_access_tokens_tokenable_index
    ON personal_access_tokens(tokenable_type, tokenable_id);

CREATE TABLE IF NOT EXISTS tanggapan (
    id_tanggapan bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pengaduan bigint NOT NULL,
    tgl_tanggapan timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tanggapan text NOT NULL,
    file_bukti varchar(255),
    id_petugas bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_bukti_2 varchar(255),
    file_bukti_3 varchar(255),
    CONSTRAINT tanggapan_id_pengaduan_foreign
        FOREIGN KEY (id_pengaduan) REFERENCES pengaduan(id_pengaduan)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT tanggapan_id_petugas_foreign
        FOREIGN KEY (id_petugas) REFERENCES petugas(id_petugas)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS tanggapan_pengaduan_index ON tanggapan(id_pengaduan);
CREATE INDEX IF NOT EXISTS tanggapan_petugas_index ON tanggapan(id_petugas);

CREATE TABLE IF NOT EXISTS permintaan_reset_password (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik char(16) NOT NULL,
    no_hp varchar(20),
    status varchar(20) NOT NULL DEFAULT 'menunggu',
    dibaca boolean NOT NULL DEFAULT false,
    catatan text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permintaan_reset_password_nik_foreign
        FOREIGN KEY (nik) REFERENCES masyarakat(nik)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT permintaan_reset_password_status_check CHECK (status IN ('menunggu', 'selesai'))
);

CREATE INDEX IF NOT EXISTS permintaan_reset_password_nik_index
    ON permintaan_reset_password(nik);

COMMIT;
